"""initial

Revision ID: 22dbb3005b07
Revises: 
Create Date: 2026-04-10 08:15:20.464427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dbb3005b07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apoderado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apoderado_rut'), 'apoderado', ['rut'], unique=True)
    op.create_table('colegio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dia_sin_almuerzo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion_consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('nivel_desde', sa.Integer(), nullable=False),
    sa.Column('nivel_hasta', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apoderado_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['apoderado_id'], ['apoderado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('modalidad_override', sa.String(length=20), nullable=True),
    sa.Column('precio_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumno_rut'), 'alumno', ['rut'], unique=True)
    op.create_table('alumno_apoderado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('apoderado_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.ForeignKeyConstraint(['apoderado_id'], ['apoderado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('modalidad', sa.String(length=20), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('consumo_id', sa.Integer(), nullable=False),
    sa.Column('monto_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['consumo_id'], ['consumo.id'], ),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago_detalle')
    op.drop_table('consumo')
    op.drop_table('alumno_apoderado')
    op.drop_index(op.f('ix_alumno_rut'), table_name='alumno')
    op.drop_table('alumno')
    op.drop_table('pago')
    op.drop_table('curso')
    op.drop_table('configuracion_consumo')
    op.drop_table('dia_sin_almuerzo')
    op.drop_table('colegio')
    op.drop_index(op.f('ix_apoderado_rut'), table_name='apoderado')
    op.drop_table('apoderado')
    # ### end Alembic commands ###
