"""add usuario_colegio

Revision ID: 97b17c66e0fd
Revises: b9c1d2e3f4a5
Create Date: 2026-07-03 00:38:34.904710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b17c66e0fd'
down_revision: Union[str, None] = 'b9c1d2e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_colegio',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'colegio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_colegio')
    # ### end Alembic commands ###
