"""rebaja tickets frecuentes

Revision ID: b304c77dd19f
Revises: c07a8b0f3ee5
Create Date: 2026-07-09 02:22:52.694078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b304c77dd19f'
down_revision: Union[str, None] = 'c07a8b0f3ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_rebaja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colegio_id', sa.Integer(), nullable=False),
    sa.Column('dias_minimos', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['colegio_id'], ['colegio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('colegio_id')
    )
    op.create_table('rebaja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rebaja')
    op.drop_table('configuracion_rebaja')
    # ### end Alembic commands ###
