"""apoderado telefono celular

Revision ID: c07a8b0f3ee5
Revises: 97b17c66e0fd
Create Date: 2026-07-03 01:48:22.492868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07a8b0f3ee5'
down_revision: Union[str, None] = '97b17c66e0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apoderado', sa.Column('telefono', sa.String(length=50), nullable=True))
    op.add_column('apoderado', sa.Column('celular', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apoderado', 'celular')
    op.drop_column('apoderado', 'telefono')
    # ### end Alembic commands ###
